NAME = phonebook
CC = g++
FLAGS = -Wall -Werror -Wextra
SRC = phonebook.cpp phonebook.class.cpp contact.class.cpp

all: $(NAME)


$(NAME):
	$(CC) $(FLAGS) $(SRC) -o $(NAME)
fclean:
	rm -f $(NAME)
re: fclean all