NAME = phonebook
CC = g++
FLAGS = -Wall -Werror -Wextra -std=c++98
SRC = phonebook.cpp phonebook.class.cpp contact.class.cpp
all: $(NAME)

$(NAME):
	$(CC) $(FLAGS) $(SRC) -o $(NAME)
fclean: 
	rm -f $(NAME)
re: fclean all